print("hello, what is your full name")
name = input()
str(name)
print("hello " + name)
print ("what is the time")
time = input()
str(time)
print("What is todays date (MM/DD/YYYY)")
date = input()
str(date)
print(name + " has been charged $9000 on " + date + " at " + time)
print('mf')
print("anyways, since you didn't fall for it, I will give u a test.")
print("The Eternal QUestion")
print("who is the best actor out of these 4?")
print("A.Robert Downey Junior")
print("B.Johnny Depp")
print("C.Charlie Chaplin")
print("D.Denzel Washington")
answer = input()
